webtalk_init -webtalk_dir C:/Users/Amadeus/simple_processor/Simple_Processor.sim/sim_1/behav/xsim/xsim.dir/CPU_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Oct 26 13:42:19 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c4b8a1f9-d2d2-490d-8939-e42929e13715" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "be08e5176f99449d9f6d05648d3f6874" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "255" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows Server 2012 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3093 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "19.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5616_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1826454275 -regid "" -xml C:/Users/Amadeus/simple_processor/Simple_Processor.sim/sim_1/behav/xsim/xsim.dir/CPU_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Amadeus/simple_processor/Simple_Processor.sim/sim_1/behav/xsim/xsim.dir/CPU_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Amadeus/simple_processor/Simple_Processor.sim/sim_1/behav/xsim/xsim.dir/CPU_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
